### ISSUE TITLE
Add manifest.json

### ISSUE THREAD

**Issue by mrstegeman** [rzr/mastodon-lite#12]
I see that you've added a manifest.json, but could you make a new release containing that file?

**Comment by rzr** [comment]
Sure I wanted to add new feature with contributor I am onboarding but this can be done afterwards.

**Comment by rzr** [comment]
It's released in:
https://github.com/rzr/mastodon-lite/releases/tag/v0.0.18

Should I use also addon builder for pure js addons too ?

**Comment by mrstegeman** [comment]
No, that’s only necessary for things with native dependencies.

**Comment by rzr** [comment]
yes that's what I guessed, I wanted to you to confirm,

From a security perspective it would be better that packages would be rebuilt by a bot somewhere...

Ok anyway mine would not work because adapter is in sub directory,

well I could relocate patches in a branch like:
https://github.com/rzr/mastodon-lite/commits/moziot/master

But this is useless for now.
